server:
  grpc:
    address: "${GRPC_ADDRESS:0.0.0.0:20000}"
    timeout: "${GRPC_TIMEOUT:30s}"
    middlewares:
      trace: true
      recover: true
      prometheus: true
      caching: true
#  service_cache:
#    enabled: true
#    provider: memory
#    lock_type: inproc
#    lock_timeout: 0.2s
data:
  database:
    type: mongo
    link: mongodb://gowing:gowing@127.0.0.1:27017/gowing
    database_name: gowing
#  redis:
#    address: "127.0.0.1:6379"
#    db: 0
#    pool_size: 50
#    min_idle_conns: 30
#    max_idle_conns: 50
#    conn_max_idle_time: 10s
#    pool_timeout: 1s
#    dial_timeout: 1s
#    read_timeout: 1s
#    write_timeout: 1s
#    lock_enabled: true
#    trace_enabled: true

log:
  level: debug
#  path: logs
otlp:
#  grpc_endpoint: "${OTLP_GRPC_ENDPOINT:localhost:4319}"
  http_endpoint: "${OTLP_HTTP_ENDPOINT:localhost:5080}"
  http_basic_auth_token: cm9vdEBleGFtcGxlLmNvbTpiV0s3eTlEUFcycjNzQTcw
  insecure: true
