dubbo:
  registries:
    nacos:
      protocol: nacos
      address: 127.0.0.1:8848
  protocols:
    triple:
      name: tri
      port: 22000
  provider:
    services:
      VideoCollectionImpl:
        # interface read from pb file
        interface: ""