// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rpc_client

import (
	"context"
	"github.com/castbox/go-guru/pkg/client"
	"github.com/castbox/go-guru/pkg/goguru/conf"
	"github.com/castbox/go-guru/pkg/util/logger"
)

// Injectors from wire.go:

func wireClient(contextContext context.Context, confClient *conf.Client, log *conf.Log, otlp *conf.Otlp) (*Clients, func(), error) {
	appMetadata := newAppMetadata()
	logLogger, err := logger.NewLogger(appMetadata, log)
	if err != nil {
		return nil, nil, err
	}
	clientConn, cleanup, err := client.NewGrpcConnection(contextContext, confClient, logLogger)
	if err != nil {
		return nil, nil, err
	}
	clients, err := NewClients(contextContext, clientConn, logLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return clients, func() {
		cleanup()
	}, nil
}
