// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsRecordNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RECORD_NOT_FOUND.String() && e.Code == 404
}

// 为某个枚举单独设置错误码
func ErrorRecordNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_RECORD_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsIdValueMissing(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ID_VALUE_MISSING.String() && e.Code == 400
}

func ErrorIdValueMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ID_VALUE_MISSING.String(), fmt.Sprintf(format, args...))
}

func IsRequestInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REQUEST_INVALID.String() && e.Code == 400
}

func ErrorRequestInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_REQUEST_INVALID.String(), fmt.Sprintf(format, args...))
}
