// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/videocollection/service/v1/video_collection_api.proto

package v1

import (
	context "context"
	proto "github.com/wesleywu/ri-service-provider/app/videocollection/service/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VideoCollection_Count_FullMethodName       = "/v1.VideoCollection/Count"
	VideoCollection_One_FullMethodName         = "/v1.VideoCollection/One"
	VideoCollection_List_FullMethodName        = "/v1.VideoCollection/List"
	VideoCollection_Get_FullMethodName         = "/v1.VideoCollection/Get"
	VideoCollection_Create_FullMethodName      = "/v1.VideoCollection/Create"
	VideoCollection_Update_FullMethodName      = "/v1.VideoCollection/Update"
	VideoCollection_Upsert_FullMethodName      = "/v1.VideoCollection/Upsert"
	VideoCollection_Delete_FullMethodName      = "/v1.VideoCollection/Delete"
	VideoCollection_DeleteMulti_FullMethodName = "/v1.VideoCollection/DeleteMulti"
)

// VideoCollectionClient is the client API for VideoCollection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoCollectionClient interface {
	Count(ctx context.Context, in *proto.VideoCollectionCountReq, opts ...grpc.CallOption) (*proto.VideoCollectionCountRes, error)
	One(ctx context.Context, in *proto.VideoCollectionOneReq, opts ...grpc.CallOption) (*proto.VideoCollectionOneRes, error)
	List(ctx context.Context, in *proto.VideoCollectionListReq, opts ...grpc.CallOption) (*proto.VideoCollectionListRes, error)
	Get(ctx context.Context, in *proto.VideoCollectionGetReq, opts ...grpc.CallOption) (*proto.VideoCollectionGetRes, error)
	Create(ctx context.Context, in *proto.VideoCollectionCreateReq, opts ...grpc.CallOption) (*proto.VideoCollectionCreateRes, error)
	Update(ctx context.Context, in *proto.VideoCollectionUpdateReq, opts ...grpc.CallOption) (*proto.VideoCollectionUpdateRes, error)
	Upsert(ctx context.Context, in *proto.VideoCollectionUpsertReq, opts ...grpc.CallOption) (*proto.VideoCollectionUpsertRes, error)
	Delete(ctx context.Context, in *proto.VideoCollectionDeleteReq, opts ...grpc.CallOption) (*proto.VideoCollectionDeleteRes, error)
	DeleteMulti(ctx context.Context, in *proto.VideoCollectionDeleteMultiReq, opts ...grpc.CallOption) (*proto.VideoCollectionDeleteMultiRes, error)
}

type videoCollectionClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoCollectionClient(cc grpc.ClientConnInterface) VideoCollectionClient {
	return &videoCollectionClient{cc}
}

func (c *videoCollectionClient) Count(ctx context.Context, in *proto.VideoCollectionCountReq, opts ...grpc.CallOption) (*proto.VideoCollectionCountRes, error) {
	out := new(proto.VideoCollectionCountRes)
	err := c.cc.Invoke(ctx, VideoCollection_Count_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCollectionClient) One(ctx context.Context, in *proto.VideoCollectionOneReq, opts ...grpc.CallOption) (*proto.VideoCollectionOneRes, error) {
	out := new(proto.VideoCollectionOneRes)
	err := c.cc.Invoke(ctx, VideoCollection_One_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCollectionClient) List(ctx context.Context, in *proto.VideoCollectionListReq, opts ...grpc.CallOption) (*proto.VideoCollectionListRes, error) {
	out := new(proto.VideoCollectionListRes)
	err := c.cc.Invoke(ctx, VideoCollection_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCollectionClient) Get(ctx context.Context, in *proto.VideoCollectionGetReq, opts ...grpc.CallOption) (*proto.VideoCollectionGetRes, error) {
	out := new(proto.VideoCollectionGetRes)
	err := c.cc.Invoke(ctx, VideoCollection_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCollectionClient) Create(ctx context.Context, in *proto.VideoCollectionCreateReq, opts ...grpc.CallOption) (*proto.VideoCollectionCreateRes, error) {
	out := new(proto.VideoCollectionCreateRes)
	err := c.cc.Invoke(ctx, VideoCollection_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCollectionClient) Update(ctx context.Context, in *proto.VideoCollectionUpdateReq, opts ...grpc.CallOption) (*proto.VideoCollectionUpdateRes, error) {
	out := new(proto.VideoCollectionUpdateRes)
	err := c.cc.Invoke(ctx, VideoCollection_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCollectionClient) Upsert(ctx context.Context, in *proto.VideoCollectionUpsertReq, opts ...grpc.CallOption) (*proto.VideoCollectionUpsertRes, error) {
	out := new(proto.VideoCollectionUpsertRes)
	err := c.cc.Invoke(ctx, VideoCollection_Upsert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCollectionClient) Delete(ctx context.Context, in *proto.VideoCollectionDeleteReq, opts ...grpc.CallOption) (*proto.VideoCollectionDeleteRes, error) {
	out := new(proto.VideoCollectionDeleteRes)
	err := c.cc.Invoke(ctx, VideoCollection_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCollectionClient) DeleteMulti(ctx context.Context, in *proto.VideoCollectionDeleteMultiReq, opts ...grpc.CallOption) (*proto.VideoCollectionDeleteMultiRes, error) {
	out := new(proto.VideoCollectionDeleteMultiRes)
	err := c.cc.Invoke(ctx, VideoCollection_DeleteMulti_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoCollectionServer is the server API for VideoCollection service.
// All implementations must embed UnimplementedVideoCollectionServer
// for forward compatibility
type VideoCollectionServer interface {
	Count(context.Context, *proto.VideoCollectionCountReq) (*proto.VideoCollectionCountRes, error)
	One(context.Context, *proto.VideoCollectionOneReq) (*proto.VideoCollectionOneRes, error)
	List(context.Context, *proto.VideoCollectionListReq) (*proto.VideoCollectionListRes, error)
	Get(context.Context, *proto.VideoCollectionGetReq) (*proto.VideoCollectionGetRes, error)
	Create(context.Context, *proto.VideoCollectionCreateReq) (*proto.VideoCollectionCreateRes, error)
	Update(context.Context, *proto.VideoCollectionUpdateReq) (*proto.VideoCollectionUpdateRes, error)
	Upsert(context.Context, *proto.VideoCollectionUpsertReq) (*proto.VideoCollectionUpsertRes, error)
	Delete(context.Context, *proto.VideoCollectionDeleteReq) (*proto.VideoCollectionDeleteRes, error)
	DeleteMulti(context.Context, *proto.VideoCollectionDeleteMultiReq) (*proto.VideoCollectionDeleteMultiRes, error)
	mustEmbedUnimplementedVideoCollectionServer()
}

// UnimplementedVideoCollectionServer must be embedded to have forward compatible implementations.
type UnimplementedVideoCollectionServer struct {
}

func (UnimplementedVideoCollectionServer) Count(context.Context, *proto.VideoCollectionCountReq) (*proto.VideoCollectionCountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedVideoCollectionServer) One(context.Context, *proto.VideoCollectionOneReq) (*proto.VideoCollectionOneRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method One not implemented")
}
func (UnimplementedVideoCollectionServer) List(context.Context, *proto.VideoCollectionListReq) (*proto.VideoCollectionListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedVideoCollectionServer) Get(context.Context, *proto.VideoCollectionGetReq) (*proto.VideoCollectionGetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVideoCollectionServer) Create(context.Context, *proto.VideoCollectionCreateReq) (*proto.VideoCollectionCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVideoCollectionServer) Update(context.Context, *proto.VideoCollectionUpdateReq) (*proto.VideoCollectionUpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedVideoCollectionServer) Upsert(context.Context, *proto.VideoCollectionUpsertReq) (*proto.VideoCollectionUpsertRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedVideoCollectionServer) Delete(context.Context, *proto.VideoCollectionDeleteReq) (*proto.VideoCollectionDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVideoCollectionServer) DeleteMulti(context.Context, *proto.VideoCollectionDeleteMultiReq) (*proto.VideoCollectionDeleteMultiRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMulti not implemented")
}
func (UnimplementedVideoCollectionServer) mustEmbedUnimplementedVideoCollectionServer() {}

// UnsafeVideoCollectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoCollectionServer will
// result in compilation errors.
type UnsafeVideoCollectionServer interface {
	mustEmbedUnimplementedVideoCollectionServer()
}

func RegisterVideoCollectionServer(s grpc.ServiceRegistrar, srv VideoCollectionServer) {
	s.RegisterService(&VideoCollection_ServiceDesc, srv)
}

func _VideoCollection_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.VideoCollectionCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCollectionServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCollection_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCollectionServer).Count(ctx, req.(*proto.VideoCollectionCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCollection_One_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.VideoCollectionOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCollectionServer).One(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCollection_One_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCollectionServer).One(ctx, req.(*proto.VideoCollectionOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCollection_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.VideoCollectionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCollectionServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCollection_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCollectionServer).List(ctx, req.(*proto.VideoCollectionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCollection_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.VideoCollectionGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCollectionServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCollection_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCollectionServer).Get(ctx, req.(*proto.VideoCollectionGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCollection_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.VideoCollectionCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCollectionServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCollection_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCollectionServer).Create(ctx, req.(*proto.VideoCollectionCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCollection_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.VideoCollectionUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCollectionServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCollection_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCollectionServer).Update(ctx, req.(*proto.VideoCollectionUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCollection_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.VideoCollectionUpsertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCollectionServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCollection_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCollectionServer).Upsert(ctx, req.(*proto.VideoCollectionUpsertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCollection_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.VideoCollectionDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCollectionServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCollection_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCollectionServer).Delete(ctx, req.(*proto.VideoCollectionDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoCollection_DeleteMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.VideoCollectionDeleteMultiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCollectionServer).DeleteMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoCollection_DeleteMulti_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCollectionServer).DeleteMulti(ctx, req.(*proto.VideoCollectionDeleteMultiReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoCollection_ServiceDesc is the grpc.ServiceDesc for VideoCollection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoCollection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VideoCollection",
	HandlerType: (*VideoCollectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Count",
			Handler:    _VideoCollection_Count_Handler,
		},
		{
			MethodName: "One",
			Handler:    _VideoCollection_One_Handler,
		},
		{
			MethodName: "List",
			Handler:    _VideoCollection_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _VideoCollection_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _VideoCollection_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VideoCollection_Update_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _VideoCollection_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VideoCollection_Delete_Handler,
		},
		{
			MethodName: "DeleteMulti",
			Handler:    _VideoCollection_DeleteMulti_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/videocollection/service/v1/video_collection_api.proto",
}
