// Code generated by protoc-gen-go-guru. DO NOT EDIT.
// versions:
//  protoc-gen-go-guru v0.2.5
// source: api/videocollection/service/v1/video_collection_api.proto

package v1

import (
	cache "github.com/castbox/go-guru/pkg/goguru/cache"
	rpcinfo "github.com/castbox/go-guru/pkg/server/rpcinfo"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func RegisterVideoCollectionGuruServer(srv VideoCollectionServer) error {
	var err error
	rpcinfo.RegisterServiceDesc(&VideoCollection_ServiceDesc, srv)
	err = rpcinfo.RegisterMethodDesc("v1.VideoCollection", "Count", &cache.CacheRule{
		Cachable: false,
		Name:     "VideoCollection",
		Ttl:      "30s",
		Key:      "",
	})
	if err != nil {
		return err
	}
	err = rpcinfo.RegisterMethodDesc("v1.VideoCollection", "One", &cache.CacheRule{
		Cachable: false,
		Name:     "VideoCollection",
		Ttl:      "30s",
		Key:      "",
	})
	if err != nil {
		return err
	}
	err = rpcinfo.RegisterMethodDesc("v1.VideoCollection", "List", &cache.CacheRule{
		Cachable: false,
		Name:     "VideoCollection",
		Ttl:      "30s",
		Key:      "",
	})
	if err != nil {
		return err
	}
	err = rpcinfo.RegisterMethodDesc("v1.VideoCollection", "Get", &cache.CacheRule{
		Cachable: false,
		Name:     "",
		Ttl:      "",
		Key:      "",
	})
	if err != nil {
		return err
	}
	err = rpcinfo.RegisterMethodDesc("v1.VideoCollection", "Create", &cache.CacheRule{
		Cachable: false,
		Name:     "",
		Ttl:      "",
		Key:      "",
	})
	if err != nil {
		return err
	}
	err = rpcinfo.RegisterMethodDesc("v1.VideoCollection", "Update", &cache.CacheRule{
		Cachable: false,
		Name:     "",
		Ttl:      "",
		Key:      "",
	})
	if err != nil {
		return err
	}
	err = rpcinfo.RegisterMethodDesc("v1.VideoCollection", "Upsert", &cache.CacheRule{
		Cachable: false,
		Name:     "",
		Ttl:      "",
		Key:      "",
	})
	if err != nil {
		return err
	}
	err = rpcinfo.RegisterMethodDesc("v1.VideoCollection", "Delete", &cache.CacheRule{
		Cachable: false,
		Name:     "",
		Ttl:      "",
		Key:      "",
	})
	if err != nil {
		return err
	}
	err = rpcinfo.RegisterMethodDesc("v1.VideoCollection", "DeleteMulti", &cache.CacheRule{
		Cachable: false,
		Name:     "",
		Ttl:      "",
		Key:      "",
	})
	if err != nil {
		return err
	}
	return nil
}
